# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: contralaviolencia
  pool: 5
  timeout: 5000
  statement_limit: 200
  host: localhost
  port: 5432
  username: contralaviolenciausuario
  password: contralaviolenciausuario1
test:
  adapter: postgresql
  database: contralaviolencia
  pool: 5
  timeout: 5000
  statement_limit: 200
  host: localhost
  port: 5432
  username: contralaviolenciausuario
  password: contralaviolenciausuario1

production:
  adapter: postgresql
  database: contralaviolencia
  pool: 5
  timeout: 5000
  statement_limit: 200
  host: localhost
  port: 5432
  username: contralaviolenciausuario
  password: contralaviolenciausuario1

